export const athenahealthProfile = {
  id: 'athenahealth',
  vendorName: 'athenahealth',
  fingerprints: {
    responseHeaders: ['x-athena-request-id', 'x-ath-correlation-id'],
    urlPatterns: ['api.preview.platform.athenahealth.com', 'athenanet.com/fhir'],
    extensions: ['http://www.athenahealth.com/fhir'],
    errorSignature: { detailedmessage: '', error: '' },
  },
  versions: {
    detect: () => 'athena-platform-current',
  },
  fhir: {
    version: 'R4',
    referralResource: 'ServiceRequest',
    authorizationResource: 'Claim',
    patientSearchParams: ['identifier', 'name', 'birthdate', 'address-postalcode'],
    specialtyCodeSystem: 'http://nucc.org/provider-taxonomy',
    authType: 'oauth2_basic',
    smartScopes: [
      'system/Patient.read',
      'system/ServiceRequest.read',
      'system/ServiceRequest.write',
      'system/Coverage.read',
    ],
    supportsWebhooks: true,
    webhookEvents: ['patient.updated', 'appointment.scheduled', 'referral.updated'],
  },
  referralWorkflow: {
    createEndpoint: 'POST /ServiceRequest',
    statusField: 'status',
    statusMap: {
      'draft':     'DRAFT',
      'active':    'SUBMITTED',
      'completed': 'COMPLETED',
      'revoked':   'CANCELLED',
    },
    notesField: 'note[0].text',
    attachmentsMethod: 'DocumentReference',
    requiresOrderingProvider: true,
    specialtyInPerformer: true,
  },
  performance: {
    rateLimitPerMin: 150,
    recommendedConcurrency: 6,
    avgResponseMs: 700,
    sandboxUrl: 'https://api.preview.platform.athenahealth.com/fhir/r4',
  },
  quirks: [
    {
      id: 'athena-practiceid-required',
      description: 'athenahealth requires practiceid in every request path — must be stored per connection',
      severity: 'high',
      workaround: 'injectPracticeIdFromConnection',
      affectedFields: ['all_requests'],
    },
    {
      id: 'athena-pagination-next-link',
      description: 'athenahealth uses nexttoken cursor pagination, not FHIR standard bundle links',
      severity: 'medium',
      workaround: 'useAthenaCursorPagination',
      affectedFields: ['list_operations'],
    },
  ],
  fieldMappings: {
    'referral.specialty':      'ServiceRequest.code.text',
    'referral.diagnosisCodes': 'ServiceRequest.reasonCode[*].coding[0].code',
    'referral.procedureCodes': 'ServiceRequest.code.coding[0].code',
    'referral.clinicalNotes':  'ServiceRequest.note[0].text',
    'patient.mrn':             'Patient.identifier[?(@.system=includes("athena"))].value',
    'patient.insuranceMemberId': 'Coverage.subscriberId',
  },
  urgencyMap: {
    'ROUTINE':   'routine',
    'URGENT':    'urgent',
    'STAT':      'stat',
    'EMERGENCY': 'stat',
  },
}
